name: Convert HTML to PDF

on:
  workflow_call:
    inputs:
      source:
        required: true
        type: string
      output:
        required: true
        type: string

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Convert HTML to PDF
        uses: narthanaj/html-to-pdf-action@v1
        with:
          source: ${{ inputs.source }}
          output: ${{ inputs.output }}
          format: A4
          orientation: portrait
          print_background: true
